services:
  testing-db:
    image: postgres:18
    container_name: testing-db
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: testing_dbt

    volumes:
      - ./script:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"